### ISSUE TITLE
The main function is not correct in windows

### ISSUE THREAD

**Issue by Mac1512** [scemino/DoomFire#1]
Hi Scemino,

I have seen that you have been involved with these effects (fire and color cycling), maybe it is what you are looking to add to engge ... or maybe I am wrong, but still, they are spectacular !!! I congratulate you for it :)

So I have started to test them in windows and I have seen some errors when compiling and executing the program in windows. I comment on them in separate issues in case you want to adapt it for windows. I tell you:

The main function, inside the main.cpp file, is not correct for windows, it could be valid with the following code:

```
#ifndef WIN32
	int main(int argc, const char** argv) {
#else
	int main(int argc, char* argv[]) {
#endif
```

Cheers :)

**Comment by scemino** [comment]
> I have seen that you have been involved with these effects (fire and color cycling), maybe it is what you are looking to add to engge ... or maybe I am wrong, but still, they are spectacular !!! I congratulate you for it :)

Actually, it was kind of vacation to do something else than working on engge, but it's kind of useful for engge, because I'm facing some issues with engge, but I needed to learn and try coding some shaders to implement them correctly in engge

> So I have started to test them in windows and I have seen some errors when compiling and executing the program in windows. I comment on them in separate issues in case you want to adapt it for windows. I tell you:
> 
> The main function, inside the main.cpp file, is not correct for windows, it could be valid with the following code:
> 
> ```
> #ifndef WIN32
> 	int main(int argc, const char** argv) {
> #else
> 	int main(int argc, char* argv[]) {
> #endif
> ```
Thank you

**Comment by Mac1512** [comment]
There is still an error in windows, the change for windows should be this:

`int main(int argc, char *argv[]) {`

otherwise it gives this link error:

![link error](https://user-images.githubusercontent.com/2179224/91643800-bab85e80-ea36-11ea-9940-6f882af48879.PNG)

**Comment by scemino** [comment]
Oh sorry I didn't see that the `const` shouldn't be here, don't hesitate to send pull-request if you want to fix it on your own next time.
