### ISSUE TITLE
The palette does not paint correctly within imgui on windows

### ISSUE THREAD

**Issue by Mac1512** [scemino/DoomFire#2]
If I compile the current source code, on windows, the palette looks like this:

![fire_fail](https://user-images.githubusercontent.com/2179224/91642877-2c8caa00-ea2f-11ea-9c2a-50cc596d8219.PNG)

To correct the problem on windows, you would have to change the drawPalette function, inside the file (DoomFireApplication.cpp), the change being the following:

```
#ifndef WIN32
          auto color = ImColor(
              static_cast<float>(*palette++) / 255.0f, static_cast<float>(*palette++) / 255.0f, static_cast<float>(*palette++) / 255.0f, 1.0f);
#else

          auto color = ImColor(palette[(i * 3 + 0) + numColorsByRow * 3 * j], palette[(i * 3 + 1) + numColorsByRow * 3 * j], palette[(i * 3 + 2) + numColorsByRow * 3 * j], 255);
#endif
```

Cheers :)

**Comment by scemino** [comment]
Wow strange, thank you for your feedback

**Comment by Mac1512** [comment]
Forget to comment, that I have compiled for 32-bit architecture, although I think it would be the same result if I compiled for 64-bit architecture.

I'm going to test the new commit (https://github.com/scemino/DoomFire/commit/9f7e0e10b5bbe847380dec0773e09bd4f43bebcf)

regards

**Comment by Mac1512** [comment]
The palette now works correctly, but you still have to change the main function, I have told you in its issue (https://github.com/scemino/DoomFire/issues/1)
